---
# APP
- hosts: "{{terralegoback_servers|default('all')}}"
  roles: [corpusops.roles/ansible_plugins]
  tasks:
  - when: ["cops_terralegoback_lifecycle_app|default(true)"]
    tags: ["cops_terralegoback_lifecycle_app"]
    block:
    - include_role: {name: terralegoback_vars, allow_duplicates: false}
    - include_role: {name: terralegoback,      allow_duplicates: false}
