---
cops_terralego_name: terralegoinstance
cops_terralego_deploy_env: "dev"
cops_terralego_docker_image_tag: "{{cops_terralego_name}}"
cops_terralego_default_docker_tag: "latest"
cops_terralego_docker_tag: "{{cops_terralego_default_docker_tag}}"
cops_terralego_tld_domain: example.com
cops_terralego_mail_domain: "{{ cops_terralego_tld_domain }}"
cops_terralego_default_gitref: "master"
cops_terralego_gitref: "{{cops_terralego_default_gitref}}"
cops_terralego_dir: "/srv/docker/{{cops_terralego_name}}back"
cops_terralego_hostname: "{{cops_terralego_deploy_env}}-terralego-{{cops_terralego_name}}.{{cops_terralego_tld_domain}}"
cops_terralego_alternate_hostname: [".{{cops_terralego_tld_domain}}"]
cops_terralego_secret_key: "SuperSecret"
cops_terralego_gateway: "{{ ansible_default_ipv4.address}}"
cops_terralego_front_hostname: "localhost"
cops_terralego_front_url: "http://{{ cops_terralego_gateway }}:9080"
cops_terralego_composename: "{{cops_terralego_name}}back"
cops_terralego_db_user: "secretJFCxwPHz99R9jIi"
cops_terralego_db_password: "secret4gzQNe3c8851VOJ"
cops_terralego_db_name: "{{cops_terralego_name}}"
cops_terralego_devmode: False
cops_terralego_build_args: "--no-cache django cron"
# backup could be remove in a-while when we have redeployed it everywhere
cops_terralego_restarted_services: "db redis django nginx backup cron"
cops_terralego_purge_volumes: [statics]
cops_terralego_sshargs: >-
  {% set k = hostvars[inventory_hostname].get(
                'ansible_ssh_private_key_file', '') %}
  {% if k%}-o IdentityFile={{k}} -o IdentitiesOnly=yes{%endif%}
  {% if (
      hostvars[inventory_hostname].ansible_connection|default('ssh')
     ) not in [ 'smart', 'local'] %}
  {{ hostvars[inventory_hostname].ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_common_args | default('') }}
  {{ hostvars[inventory_hostname].ansible_ssh_extra_args | default('') }}
  {% endif %}
cops_terralego_build: false
cops_terralego_pull: true
cops_terralego_registries: []
#- {registry: registry.foo.net, username: foo, password: bar}
cops_terralego_compose_files: [docker-compose.yml, docker-compose-prod.yml]
cops_terralego_dc:
  docker-compose {% for i in cops_terralego_compose_files %} -f {{i}}{% endfor %}
  -p "{{cops_terralego_composename}}"
cops_terralego_default_from_email: noreply@{{cops_terralego_hostname}}
cops_terralego_server_email: "{{cops_terralego_default_from_email}}"
cops_terralego_mailcatcher_user: mailcatcher
cops_terralego_mailcatcher_password: mailcatcher
cops_terralego_email_server: mailcatcher
cops_terralego_email_host_user: ''
cops_terralego_email_host_password: ''
cops_terralego_email_host_port: 1025
cops_terralego_email_use_tls: 'no'
# free form for params inside dockerenv
cops_terralego_sentry_tags: ["{{cops_terralego_deploy_env}}"]
cops_terralego_sentry_dsn: ''
cops_terralego_docker_env_freeform: |-
  {{ cops_terralego_docker_env_defaults}}
  {{ cops_terralego_docker_env_extra}}
cops_terralego_docker_env_defaults: |-
  HOSTNAME="${PROJECT_NAME}"
  FRONT_URL={{ cops_terralego_front_url }}
  DJANGO__FRONT_URL={{ cops_terralego_front_url }}
  #
  # This need to be changed in production
  SECRET_KEY={{ cops_terralego_secret_key }}
  # db
  POSTGRES_USER={{ cops_terralego_db_user }}
  POSTGRES_DB={{ cops_terralego_db_name }}
  POSTGRES_PASSWORD={{cops_terralego_db_password }}
  PGPASSWD={{cops_terralego_db_password }}
  # cors
  DJANGO__CORS_ORIGIN_WHITELIST={{(
    [cops_terralego_hostname, '0.0.0.0', '.{0}'.format(cops_terralego_hostname)]+
    cops_terralego_alternate_hostname
  )|join('-|_')}}
  DJANGO__ALLOWED_HOSTS={{(
    [cops_terralego_hostname, '.{0}'.format(cops_terralego_hostname)]+
    cops_terralego_alternate_hostname
  )|join('-|_')}}
  DJANGO__DEPLOY_ENV={{cops_terralego_deploy_env}}
  {% if cops_terralego_sentry_dsn %}
  DJANGO__SENTRY_DSN={{cops_terralego_sentry_dsn}}
  DJANGO__SENTRY_TAGS={{cops_terralego_sentry_tags|join(',')}}
  {% endif %}
  {% if cops_terralego_devmode %}
  DJANGO__CORS_ORIGIN_ALLOW_ALL=y
  DJANGO__DEBUG=y
  {% endif %}
  DJANGO__DEFAULT_FROM_EMAIL={{ cops_terralego_default_from_email }}
  DJANGO__SERVER_EMAIL={{ cops_terralego_server_email }}
  DJANGO__EMAIL_HOST={{cops_terralego_email_server}}
  DJANGO__EMAIL_PORT={{cops_terralego_email_host_port}}
  DJANGO__EMAIL_HOST_USER={{cops_terralego_email_host_user}}
  DJANGO__EMAIL_HOST_PASSWORD={{cops_terralego_email_host_password}}
  MAILCATCHER_USER={{cops_terralego_mailcatcher_user}}
  MAILCATCHER_PASSWORD={{cops_terralego_mailcatcher_password}}
  {{ cops_terralego_docker_env_extra}}
cops_terralego_dotenv: |-
  APP_TYPE=django
  DJANGO_SETTINGS_MODULE=project.settings.instances.{{cops_terralego_deploy_env}}
  DJANGO_NAME={{ cops_terralego_name }}
  COMPOSE_PROJECT_NAME={{cops_terralego_composename}}
  CI_COMMIT_SHA={{cops_terralego_gitref}}
  DJANGO_IMAGE={{ cops_terralego_docker_image }}
  DJANGO_IMAGE_VERSION={{cops_terralego_docker_tag}}
cops_terralego_dotenv_extra: ""
# free form for params inside dockerenv
cops_terralego_docker_env_extra: ""
# free form for params inside local.py
cops_terralego_localpy_extra: ""
# Normally playbook is in ./.ansible/playbooks
cops_terralego_code_dir: "{{playbook_dir}}/../.."
cops_terralego_code_rsync_opts: [
    "-azv",
    # include deploy projects base code
    "--include", "local/*-deploy",
    "--exclude", ".ansible",
    "--exclude", "local/*",
    "--exclude", ".git",
    "--exclude", ".tox",
    "--exclude", ".env",
    "--exclude", "docker.env"]
